apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  namespace: surya-namespace
  labels:
    type: something
spec:
  replicas: 5
  template:
    metadata:
      name: surya-rc-pod
      namespace: surya-namespace
      labels:
        app: someapp
        type: something
    spec:
      containers:
        - name: surya-nginx
          image: nginx:latest
