apiVersion: v1
kind: LimitRange
metadata:
  name: sample-limitrange
spec:
  limits:
  - default:
      cpu: "100m"
      memory: "256Mi"
    defaultRequest:
      cpu: "50m"
      memory: "128Mi"
    type: Container
